# Generated by Django 4.2.27 on 2025-12-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='通り名')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='スラッグ')),
            ],
            options={
                'verbose_name': '通り',
                'verbose_name_plural': '通り',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='店舗名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='dicon_app.street', verbose_name='通り')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'unique_together': {('street', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dicon_app.shop', verbose_name='店舗'),
        ),
    ]
