# Generated by Django 4.2.27 on 2025-12-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0002_street_shop_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='サブタイトル')),
                ('link_url', models.CharField(max_length=200, verbose_name='リンク先URL')),
                ('order', models.IntegerField(default=1, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
            ],
            options={
                'verbose_name': 'トップ告知スライド',
                'verbose_name_plural': 'トップ告知スライド',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='特売'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='特売価格'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='セット名')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('products', models.ManyToManyField(blank=True, related_name='sets', to='dicon_app.product')),
            ],
            options={
                'verbose_name': 'おすすめセット',
                'verbose_name_plural': 'おすすめセット',
            },
        ),
    ]
