# Generated by Django 4.2.27 on 2026-01-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0004_alter_product_options_alter_heroslide_link_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='line_url',
            field=models.URLField(blank=True, null=True, verbose_name='LINEリンク'),
        ),
    ]
