# Generated by Django 4.2.27 on 2026-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0005_shop_line_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='スラッグ')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('summary', models.CharField(blank=True, max_length=160, verbose_name='一言説明')),
                ('body', models.TextField(blank=True, verbose_name='詳細')),
                ('category', models.CharField(choices=[('food', '食'), ('experience', '体験'), ('kids', '子ども'), ('sale', '特売'), ('season', '季節'), ('other', 'その他')], default='season', max_length=20, verbose_name='カテゴリ')),
                ('image', models.CharField(blank=True, max_length=200, verbose_name='画像（staticパス）')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='場所')),
                ('map_url', models.URLField(blank=True, verbose_name='地図URL')),
                ('apply_url', models.URLField(blank=True, verbose_name='申込URL')),
                ('share_text', models.CharField(blank=True, max_length=120, verbose_name='シェア文（任意）')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ピックアップ')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'イベント',
                'verbose_name_plural': 'イベント',
                'ordering': ['start_date', '-created_at'],
            },
        ),
    ]
