# Generated by Django 4.2.27 on 2026-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('food', '食'), ('experience', '体験'), ('kids', '子ども'), ('sale', '特売'), ('season', '季節'), ('other', 'その他'), ('night', 'ナイト屋台'), ('tasting', '試食リレー'), ('retro', 'レトロ歓迎'), ('rainy', '雨の日')], default='season', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
