# Generated by Django 4.2.27 on 2026-01-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0007_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announce_from',
            field=models.DateField(blank=True, help_text='空なら即表示', null=True, verbose_name='告知開始日'),
        ),
        migrations.AddField(
            model_name='event',
            name='announce_until',
            field=models.DateField(blank=True, help_text='空ならずっと表示', null=True, verbose_name='告知終了日'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_regular',
            field=models.BooleanField(default=False, help_text='曜日イベントなど、常時表示したいもの', verbose_name='定番（繰り返し）'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_text',
            field=models.CharField(blank=True, help_text='例：毎週金曜 17:00〜 / 毎月第2土曜 / 5の付く日', max_length=120, verbose_name='開催パターン（表示用）'),
        ),
    ]
