# Generated by Django 4.2.27 on 2026-01-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0008_event_announce_from_event_announce_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
    ]
