# Generated by Django 4.2.27 on 2026-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0012_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル（管理用）')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='スライド画像')),
                ('link_url', models.URLField(blank=True, help_text='クリックした時の飛び先（空欄でもOK）', null=True, verbose_name='リンク先URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
            ],
            options={
                'verbose_name': 'トップ画像スライド',
                'verbose_name_plural': 'トップ画像スライド',
            },
        ),
        migrations.AlterModelOptions(
            name='street',
            options={},
        ),
        migrations.RemoveField(
            model_name='street',
            name='slug',
        ),
        migrations.AddField(
            model_name='street',
            name='color',
            field=models.CharField(default='#6c757d', help_text='カラーコード（例：#ff9800）', max_length=20, verbose_name='テーマカラー'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=100, verbose_name='通り名'),
        ),
    ]
