# Generated by Django 4.2.27 on 2026-01-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0013_topslide_alter_street_options_remove_street_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetable', '野菜・果物'), ('meat', 'お肉・惣菜'), ('fish', 'お魚'), ('other', 'その他')], default='other', max_length=20),
        ),
    ]
