# Generated by Django 4.2.27 on 2026-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0014_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopSlide',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/', verbose_name='スライド画像'),
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('vegetable', '野菜・果物'), ('meat', 'お肉・惣菜'), ('fish', 'お魚'), ('bread', 'パン・ケーキ・菓子'), ('dry', '乾物・お茶'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_text',
            field=models.CharField(blank=True, help_text='例：毎週金曜 17:00〜', max_length=120, verbose_name='開催パターン（表示用）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetable', '野菜・果物'), ('meat', 'お肉・惣菜'), ('fish', 'お魚'), ('bread', 'パン・ケーキ・菓子'), ('dry', '乾物・お茶'), ('other', 'その他')], default='other', max_length=20),
        ),
    ]
