# Generated by Django 4.2.27 on 2026-01-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0015_delete_topslide_heroslide_image_shop_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Googleマップで右クリックしてコピーした緯度（左側の数字）', null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Googleマップで右クリックしてコピーした経度（右側の数字）', null=True, verbose_name='経度'),
        ),
    ]
