# Generated by Django 4.2.27 on 2026-01-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0016_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(max_length=200, verbose_name='説明文')),
                ('image', models.ImageField(upload_to='home_pickup/', verbose_name='画像')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='バッジテキスト')),
                ('price_text', models.CharField(max_length=50, verbose_name='価格テキスト')),
                ('link_button_text', models.CharField(default='詳しく見る', max_length=50, verbose_name='リンクボタンの文字')),
                ('link_url_name', models.CharField(help_text='例: dicon_app:set_list', max_length=100, verbose_name='リンク先のURL名')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど前に表示されます', verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開する')),
            ],
            options={
                'verbose_name': 'トップページピックアップ',
                'verbose_name_plural': 'トップページピックアップ',
                'ordering': ['order'],
            },
        ),
    ]
