# Generated by Django 4.2.27 on 2026-01-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0017_homepickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sets/', verbose_name='セット画像'),
        ),
        migrations.AddField(
            model_name='set',
            name='price',
            field=models.IntegerField(default=0, help_text='セット全体の税込価格を入力してください', verbose_name='セット価格'),
        ),
    ]
