# Generated by Django 4.2.27 on 2026-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0018_set_image_set_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明文')),
                ('price_text', models.CharField(help_text='例: ¥500〜、プライスレス、相談無料', max_length=50, verbose_name='価格表示')),
                ('image', models.ImageField(upload_to='concierge/', verbose_name='画像')),
                ('badge_text', models.CharField(blank=True, help_text='例: 1人前〜、冬限定', max_length=20, verbose_name='タグ（右上）')),
                ('link_url', models.CharField(blank=True, help_text='例: /sets/morning-set/ や #consult など', max_length=200, verbose_name='リンク先URL')),
                ('order', models.IntegerField(default=0, help_text='小さい数字ほど先に表示されます', verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'コンシェルジュ項目',
                'verbose_name_plural': 'コンシェルジュ項目',
            },
        ),
    ]
