# Generated by Django 4.2.27 on 2026-01-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0019_conciergeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='パートナー名')),
                ('description', models.TextField(blank=True, verbose_name='紹介文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='ロゴ・画像')),
                ('url', models.URLField(blank=True, verbose_name='WebサイトURL')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '認定パートナー',
                'verbose_name_plural': '認定パートナー',
            },
        ),
        migrations.AlterModelOptions(
            name='homepickup',
            options={'ordering': ['order'], 'verbose_name': '【おばちゃん】コンシェルジュ項目', 'verbose_name_plural': '【おばちゃん】コンシェルジュ項目'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': '【管理栄養士】献立セット', 'verbose_name_plural': '【管理栄養士】献立セット'},
        ),
    ]
