# Generated by Django 4.2.27 on 2026-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0020_partner_alter_homepickup_options_alter_set_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('cleaning', 'お掃除'), ('repair', '修理・修繕'), ('garden', '庭仕事'), ('clothing', '洋服・靴'), ('painting', '外壁塗装'), ('helper', 'ヘルパー'), ('others', 'その他')], default='others', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
