# Generated by Django 4.2.27 on 2026-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0021_partner_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciergeitem',
            options={'verbose_name': '【おばちゃん】コンシェルジュ項目', 'verbose_name_plural': '【おばちゃん】コンシェルジュ項目'},
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='price_text',
        ),
        migrations.AddField(
            model_name='conciergeitem',
            name='answer',
            field=models.TextField(default='', verbose_name='おばちゃんの回答'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conciergeitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterField(
            model_name='conciergeitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル（相談内容）'),
        ),
        migrations.CreateModel(
            name='ManagerDietitianSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='セット名')),
                ('slug', models.SlugField(help_text='URLの一部になります（例: liver-care）', unique=True, verbose_name='スラッグ')),
                ('category', models.CharField(choices=[('beauty', '美容・デトックス'), ('health', '健康維持・数値改善'), ('speedy', '時短・忙しい人向け'), ('diet', '糖質制限・ダイエット'), ('reward', '週末のご褒美')], default='health', max_length=20, verbose_name='カテゴリ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sets/', verbose_name='セット画像')),
                ('price', models.IntegerField(default=0, help_text='セット全体の税込価格を入力してください', verbose_name='セット価格')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='dicon_app.product', verbose_name='セットに含まれる商品')),
            ],
            options={
                'verbose_name': '【管理栄養士】献立セット',
                'verbose_name_plural': '【管理栄養士】献立セット',
            },
        ),
    ]
