# Generated by Django 4.2.27 on 2026-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0022_alter_conciergeitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='メニュー名')),
                ('description', models.TextField(verbose_name='説明文')),
                ('image', models.ImageField(upload_to='consult/', verbose_name='画像')),
                ('preset_id', models.CharField(help_text='リンク先の識別ID（例: fish, bbq, sasagaki, curry）', max_length=50, verbose_name='プリセットID')),
                ('color_theme', models.CharField(choices=[('primary', '青（魚など）'), ('danger', '赤（肉・BBQなど）'), ('success', '緑（野菜・下処理など）'), ('warning', '黄（カレー・その他）')], default='primary', max_length=20, verbose_name='テーマカラー')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='表示')),
            ],
            options={
                'verbose_name': '【ホーム】相談メニュー',
                'verbose_name_plural': '【ホーム】相談メニュー',
                'ordering': ['order'],
            },
        ),
    ]
