# Generated by Django 4.2.27 on 2026-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0023_consultationitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciergeitem',
            options={'verbose_name': '【おばちゃん】コンシェルジュ回答', 'verbose_name_plural': '【おばちゃん】コンシェルジュ回答'},
        ),
        migrations.AlterModelOptions(
            name='consultationitem',
            options={'verbose_name': '【ホーム】相談メニュー', 'verbose_name_plural': '【ホーム】相談メニュー'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント', 'verbose_name_plural': 'イベント'},
        ),
        migrations.AlterModelOptions(
            name='homepickup',
            options={'verbose_name': '【おばちゃん】コンシェルジュ項目', 'verbose_name_plural': '【おばちゃん】コンシェルジュ項目'},
        ),
        migrations.RemoveField(
            model_name='conciergeitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='consultationitem',
            name='color_theme',
        ),
        migrations.RemoveField(
            model_name='consultationitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='event',
            name='announce_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='announce_until',
        ),
        migrations.RemoveField(
            model_name='event',
            name='apply_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='body',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_regular',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='schedule_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='share_text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='heroslide',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='homepickup',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='homepickup',
            name='link_button_text',
        ),
        migrations.RemoveField(
            model_name='homepickup',
            name='price_text',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='url',
        ),
        migrations.AlterField(
            model_name='conciergeitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='consultationitem',
            name='preset_id',
            field=models.CharField(max_length=50, verbose_name='プリセットID'),
        ),
        migrations.AlterField(
            model_name='homepickup',
            name='link_url_name',
            field=models.CharField(max_length=100, verbose_name='リンク先のURL名'),
        ),
        migrations.AlterField(
            model_name='homepickup',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AlterField(
            model_name='set',
            name='price',
            field=models.IntegerField(default=0, verbose_name='セット価格'),
        ),
        migrations.AlterField(
            model_name='set',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='スラッグ'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
        migrations.DeleteModel(
            name='ManagerDietitianSet',
        ),
    ]
