# Generated by Django 4.2.27 on 2026-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0024_alter_conciergeitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conciergeitem',
            options={'ordering': ['order'], 'verbose_name': '【おばちゃん】コンシェルジュ回答', 'verbose_name_plural': '【おばちゃん】コンシェルジュ回答'},
        ),
        migrations.AlterModelOptions(
            name='consultationitem',
            options={'ordering': ['order'], 'verbose_name': '【ホーム】相談メニュー', 'verbose_name_plural': '【ホーム】相談メニュー'},
        ),
        migrations.AlterModelOptions(
            name='homepickup',
            options={'ordering': ['order'], 'verbose_name': '【おばちゃん】コンシェルジュ項目', 'verbose_name_plural': '【おばちゃん】コンシェルジュ項目'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': '認定パートナー', 'verbose_name_plural': '認定パートナー'},
        ),
        migrations.AddField(
            model_name='conciergeitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='consultationitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('food', '食'), ('experience', '体験'), ('kids', '子ども'), ('sale', '特売'), ('season', '季節'), ('other', 'その他')], default='season', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='homepickup',
            name='price_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='価格テキスト'),
        ),
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('cleaning', 'お掃除'), ('repair', '修理・修繕'), ('others', 'その他')], default='others', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, verbose_name='WebサイトURL'),
        ),
        migrations.AddField(
            model_name='set',
            name='category',
            field=models.CharField(choices=[('beauty', '美容・デトックス'), ('health', '健康維持・数値改善'), ('speedy', '時短・忙しい人向け'), ('diet', '糖質制限・ダイエット'), ('reward', '週末のご褒美')], default='health', max_length=20, verbose_name='カテゴリ'),
        ),
    ]
