# Generated by Django 4.2.27 on 2026-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0025_alter_conciergeitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepickup',
            name='target_pk',
            field=models.IntegerField(blank=True, help_text='詳細へ飛ばしたい商品のIDを入れて', null=True, verbose_name='対象のID(pk)'),
        ),
    ]
