# Generated by Django 4.2.27 on 2026-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicon_app', '0026_homepickup_target_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepickup',
            name='target_pk',
        ),
    ]
