"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# import dj_database_url #インポートいずれ要る
import os
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# envファイルを読み込む
#load_dotenv(os.path.join(BASE_DIR,'.env')) #dr
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-dq1lcrq0*ql5h5s*9kzi85or11m*vp0bvxb!^7hrnmtv39h6bb'
SECRET_KEY = os.environ.get('SECRET_KEY') # .envから読み込むように変更

# SECURITY WARNING: don't run with debug turned on in production!

# # .envから読み込む（なければFalseになる安全策）
# DEBUG = os.environ.get('DEBAG','False') == 'True'
# # 許可するドメイン。本番ではRenderのURLが入る。
# # '*'波全許可だが、今回は簡易的に設定（実務ではドメイン指定推奨）
# ALLOWED_HOSTS = ['*']

DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dicon_app',
    "payments",
    "orders",
    'accounts',  # ← 追加12/29
    # 'accounts.apps.AccountsConfig', #念の為
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # これを追加！
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# いずれ修正すること12/21（templatesフォルダの定義を追加）
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# デフォルトはSQLite（開発用）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# #本番環境
# db_from_env = dj_database_url.config(conn_max_age=600)
# DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

#12/24追加
STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ログイン後に飛ぶ先（デフォルトの /accounts/profile/ をやめる）
LOGIN_REDIRECT_URL = "dicon_app:home"

# ログアウト後の戻り先（好みで home か login）
LOGOUT_REDIRECT_URL = "dicon_app:home"

# login_required() などで未ログイン時に飛ばす先（任意だけど入れとくと安定）
LOGIN_URL = "accounts:login"


AUTHENTICATION_BACKENDS = [
    # "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend", # 一応残しておくと安心12/30
]


# ========================
# 画像アップロード用の設定1/20
# ========================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# 本番環境（Render）用の設定
# ==========================================
import os
import dj_database_url

# データベース設定（RenderではPostgreSQL、手元ではSQLiteを使う自動切替）
default_db_config = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

DATABASES = {
    'default': dj_database_url.config(default='sqlite:///db.sqlite3', conn_max_age=600)
}

# 静的ファイルと画像の設定（WhiteNoise対応）
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 画像ファイル（media）の設定
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Render環境でのセキュリティ設定
if 'RENDER' in os.environ:
    DEBUG = False
    ALLOWED_HOSTS = ['*']