# Generated by Django 4.2.27 on 2025-12-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '決済処理中'), ('success', '決済成功'), ('cancel', '決済失敗')], max_length=10),
        ),
    ]
