# Generated by Django 4.2.27 on 2025-12-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '決済処理中'), ('success', '決済成功'), ('cancel', '決済失敗')], default='pending', max_length=10),
        ),
    ]
